### ISSUE TITLE
建议可以在blog里增加评论功能

### ISSUE THREAD

**Issue by longranger2** [PFCCLab/blog#23]
具体实现可以参考这个：
- https://giscus.app/zh-CN

效果如下：
- https://www.hello-algo.com/chapter_introduction/algorithms_are_everywhere/

<img width="1089" alt="image" src="https://github.com/PFCCLab/blog/assets/52858395/c7b66c34-f2ce-43d2-86f3-12c21059204c">

**Comment by SigureMo** [comment]
个人博客评论的各种方案我都知道，但

**我不认为一个社区博客需要什么评论，这不是个人博客**

个人希望本博客贴近于国际化社区的博客形式，而不是国内的那种个人博客、文章的形式，不接受类似的需求
